# Generated by Django 6.0.4 on 2026-04-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio')], max_length=50)),
                ('muscle', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], max_length=50)),
                ('instructions', models.TextField()),
                ('safety_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=50)),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users'),
        ),
        migrations.CreateModel(
            name='comments_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
            ],
        ),
        migrations.CreateModel(
            name='calendar_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('workout', 'Workout'), ('rest', 'Rest')], max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
            ],
        ),
        migrations.CreateModel(
            name='workout_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('total_time', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
            ],
        ),
        migrations.CreateModel(
            name='exercises_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('weight', models.FloatField()),
                ('reps', models.FloatField()),
                ('duration', models.DurationField()),
                ('utc_time', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
                ('workout_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.workout_history')),
            ],
        ),
        migrations.CreateModel(
            name='workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.users')),
            ],
        ),
        migrations.AddField(
            model_name='workout_history',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.workouts'),
        ),
        migrations.CreateModel(
            name='workout_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('duration', models.DurationField()),
                ('break_between', models.DurationField()),
                ('break_after', models.DurationField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.exercises')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.workouts')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbro.workouts'),
        ),
    ]
