# Generated by Django 6.0.4 on 2026-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbro', '0002_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='muscle',
            field=models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('chest', 'Chest')], max_length=50),
        ),
    ]
