# Generated by Django 6.0.6 on 2026-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbro', '0005_calendar_events_workout_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='name',
            field=models.CharField(default='Mój Trening', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='type',
            field=models.CharField(choices=[('reps', 'Reps'), ('duration', 'Duration')], max_length=50),
        ),
    ]
