# Generated by Django 6.0.6 on 2026-06-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbro', '0006_workouts_description_workouts_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_events',
            name='time_begin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
