# Generated by Django 6.0.6 on 2026-06-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbro', '0007_calendar_events_time_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_events',
            name='repeat_interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
