# Generated by Django 6.0.6 on 2026-06-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymbro', '0004_initial_data'),
        ('gymbro', '0008_calendar_events_repeat_interval'),
    ]

    operations = [
    ]
