# Generated by Django 6.0.6 on 2026-06-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbro', '0009_merge_20260616_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_events',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=20),
        ),
    ]
