import { TrainingItem } from "../../../ReusableComponents/ComplexTypes";

export const dummyTrainings: TrainingItem[] = [
    {
      id: "1",
      title: "Leg Day",
      description: "NIG",
      muscles: "Leg, Triceps, Biceps",
      time: "14:30-18:50",
      exercisesCount: 8,
      duration: "4 h 20 min",
      exercises: [
        {
          id: "e1",
          name: "Cardio",
          muscle: ["Heart"],
          detail: "45 min",
          order: 1,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: false,
        },
        {
          id: "e2",
          name: "Incline Bench Press",
          muscle: ["Biceps"],
          detail: "4x12",
          order: 2,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: true,
        },
        {
          id: "e3",
          name: "Cardio",
          muscle: ["Heart"],
          detail: "45 min",
          order: 3,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: false,
        },
        {
          id: "e4",
          name: "Incline Bench Press",
          muscle: ["Biceps"],
          detail: "4x12",
          order: 4,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: true,
        },
      ],
      isPublic: true,
    },
    {
      id: "2",
      title: "abscdjk",
      description:
        "aasodsjidajs odjoi asdjioasjd ajosdjioasdji asjidaosjdji aosdjoas jdasjdjaosdjasj dasjdjaosdjioasdjoasjd asjodjoiasdjiasjdja sodjiaosdjoasjdasjdjasdjioasdji oasjdasdjas doasdaasodsjid ajsodjo iasdjioa sjdajosdji oasdj iasjidaosjd jiaosdjoa sjdasjdjaos djasjdasjdjaosdjio asdjoa sjdasj aasodsjidajs odjoi asdjioasjd ajosdjioasdji asjidaosjdji aosdjoas jdasjdjaosdjasj dasjdjaosdjioasdjoasjd asjodjoiasdjiasjdja sodjiaosdjoasjdasjdjasdjioasdji oasjdasdjas doasdaasodsjid ajsodjo iasdjioa sjdajosdji oasdj iasjidaosjd jiaosdjoa sjdasjdjaos djasjdasjdjaosdjio asdjoa sjdasj aasodsjidajs odjoi asdjioasjd ajosdjioasdji asjidaosjdji aosdjoas jdasjdjaosdjasj dasjdjaosdjioasdjoasjd asjodjoiasdjiasjdja sodjiaosdjoasjdasjdjasdjioasdji oasjdasdjas doasdaasodsjid ajsodjo iasdjioa sjdajosdji oasdj iasjidaosjd jiaosdjoa sjdasjdjaos djasjdasjdjaosdjio asdjoa sjdasj ",
      muscles: "Leg, Triceps, Biceps",
      time: "14:30-18:50",
      exercisesCount: 8,
      duration: "4 h 20 min",
      exercises: [
        {
          id: "x1",
          name: "Cardio",
          muscle: ["Heart"],
          detail: "45 min",
          order: 3,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: false,
        },
        {
          id: "x2",
          name: "Incline Bench Press",
          muscle: ["Biceps"],
          detail: "4x12",
          order: 4,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: true,
        },
      ],
      isPublic: true,
    },
    {
      id: "3",
      title: "Leg Day",
      description: "ER",
      muscles: "Leg, Triceps, Biceps",
      time: "14:30-18:50",
      exercisesCount: 8,
      duration: "4 h 20 min",
      exercises: [
        {
          id: "c1",
          name: "Cardio",
          muscle: ["Heart"],
          detail: "45 min",
          order: 3,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: false,
        },
        {
          id: "c2",
          name: "Incline Bench Press",
          muscle: ["Biceps"],
          detail: "4x12",
          order: 4,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: true,
        },
      ],
      isPublic: true,
    },
  ];

export const dummyTrainings2: TrainingItem[] = [
    {
      id: "1",
      title: "Second Day",
      description: "NIG",
      muscles: "Leg, Triceps, Biceps",
      time: "14:30-18:50",
      exercisesCount: 8,
      duration: "4 h 20 min",
      exercises: [
        {
          id: "e1",
          name: "Cardio",
          muscle: ["Heart"],
          detail: "45 min",
          order: 1,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: false,
        },
        {
          id: "e2",
          name: "Incline Bench Press",
          muscle: ["Biceps"],
          detail: "4x12",
          order: 2,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: true,
        },
        {
          id: "e3",
          name: "Cardio",
          muscle: ["Heart"],
          detail: "45 min",
          order: 3,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: false,
        },
        {
          id: "e4",
          name: "Incline Bench Press",
          muscle: ["Biceps"],
          detail: "4x12",
          order: 4,
          type: "exercise",
          innerBreakDuration: "1 min 30 sec",
          isRepeating: true,
        },
      ],
      isPublic: false,
    },
  ];